export const RECEIVE_INITIAL_GEOLOCATION = 'RECEIVE_INITIAL_GEOLOCATION';
export const REJECT_INITIAL_GEOLOCATION = 'REJECT_INITIAL_GEOLOCATION';
export const RECEIVE_GM_GEOLOCATION = 'RECEIVE_GM_GEOLOCATION';
export const LOAD_MAP_SCRIPT = 'LOAD_MAP_SCRIPT';
export const REJECTION = 'rejection';